services:
  app:
    networks:
      - conduit-network
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.conduit-app.rule=Host(`${SERVER_DOMAIN:-conduit.kjaymiller.dev}`)"
      - "traefik.http.routers.conduit-app.entrypoints=websecure"
      - "traefik.http.routers.conduit-app.tls=true"
      - "traefik.http.routers.conduit-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.conduit-app.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik_default"

networks:
  traefik_default:
    external: true
